server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # ✅ Important: load standard MIME map (fixes .mjs -> application/javascript)
  include /etc/nginx/mime.types;

  # ✅ Extra safety: explicitly map mjs
  types {
    application/javascript js mjs;
    application/wasm wasm;
  }

    # --- Version endpoint ---
  location /ver {
      alias /usr/share/nginx/html/ver.json;
      default_type application/json;
      add_header Cache-Control "no-store";
  }


  location / {
    try_files $uri $uri/ /index.html;
  }

  # Optional: cache hashed Vite assets
  location /assets/ {
    try_files $uri =404;
    add_header Cache-Control "public, max-age=31536000, immutable";
  }
}
